### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [JoeTreezy/date-a-scientist#2]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good job, your code runs without any errors.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ Good job making some charts exploring the data, and looking at relationships between different variables. A little more exploration of your data would have been nice, especially the variables that you're interested in -- this initial data exploration can help you determine if your research questions are worth asking.
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ You're off to a good start, but you didn't finish your SVM analysis. It's not a problem that your data is not linearly separable, you just don't want to use the 'linear' kernel in that case. Also, for you regression, I'm not sure what you mean when you say you could not produce a meaningful plot.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ First of all, it's best to not include code chunks in your presentation, as they're hard to read if the reader can't run the code themselves! Your conclusion that your algorithms could not make accurate predictions was correct, and you support those conclusions by showing the accuracy and plots. It would have been better if you had explained why your particular algorithms are well-suited for your research questions/explained what the algorithms themselves are doing.

### Criteria 5: Code formatting
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your code is formatted nicely
 
### Overall Score: 15/20
In general, you're off to a good start but your analyses were incomplete. Good job beginning to explore the data, but it would have been better if you had explored the data as a way to motivate your research questions.

**Comment by JoeTreezy** [comment]
Hi,

My code is uploaded but I didn't save each step in my process; I thought the expectation was just to create a powerpoint with the data so I overwrote some of the code i wrote to make the graphs and the regression pieces. All that I have left is the SVM model which i struggled the most with. Apologies, but it wasn't clear I was supposed to upload the code. It does not mention this in the instructions.md file.

**Comment by JoeTreezy** [comment]
@mackenzieyoung is there something else I need to do?

**Comment by mackenzieyoung** [comment]
Nope, I just updated it! Sorry for the delay
